### ISSUE TITLE
Inside Track audio Not stopping

### ISSUE THREAD

**Issue by xtxvxtx** [Andyauk/doj-casino-old#1]
After pressing backspace to close inside track the horse race audio is not stopping. Only if resource is restarted it stops.

**Comment by Andyauk** [comment]
> After pressing backspace to close inside track the horse race audio is not stopping. Only if resource is restarted it stops.

yes its a known issue, its never been fixed, I was looking into it for so long, it don't happen all the time. I used to find restarting, or running up the road a bit used to help.

**Comment by xtxvxtx** [comment]
True no biggie, was looking in the client.lua to see if I could disable the audio all together but no luck lol. Thanks for the script!
